### ISSUE TITLE
https://download.eclipse.org/justj/?file=gmf-notation shows very little

### ISSUE THREAD

**Issue by ewillink** [eclipse-justj/justj.tools#1]
GMF Notation seems to have an irregular naming convention so that https://download.eclipse.org/justj/?file=gmf-notation shows nothing useful whereas https://download.eclipse.org/oomph/archive/p2-index/modeling.gmf-runtime.html shows prolific content.

**Comment by ewillink** [comment]
The above comment confuses gmf-runtime and gmf-notation both of which failed to browse.

But the SimRel aggregation shows that both exist

16:18:41  Adding child meta-data repository https://download.eclipse.org/modeling/gmp/gmf-runtime/updates/releases/R202311130907
16:18:41  Adding child meta-data repository https://download.eclipse.org/modeling/gmp/gmf-notation/updates/releases/R202211151334

**Comment by merks** [comment]
`gmf-runtime` has contents:

-https://download.eclipse.org/justj/?file=gmf-runtime

`gmf-notation` does not:

- https://download.eclipse.org/justj/?file=gmf-notation 

Both appear to be **ancient**.

The other two URLs you mention do have contents:

- https://download.eclipse.org/justj/?file=modeling/gmp/gmf-runtime/updates/releases/R202311130907
- https://download.eclipse.org/justj/?file=modeling/gmp/gmf-notation/updates/releases/R202211151334

I'm not sure what is failing to browse.  I don't see anything wrong.

I can recommend that you setup a job that a copy of this one:

https://ci.eclipse.org/simrel/view/All/job/simrel.releng.ssh/

So that you can directly look at the file system contents via a "poor man's shell".
