### ISSUE TITLE
Incomplete Install

### ISSUE THREAD

**Issue by ewillink** [eclipse-justj/justj.tools#11]
After installing, or rather re-installing JustJ Tools and JustJ Tools Developer Resources from https://download.eclipse.org/justj/tools/updates/nightly/latest the install seems incomplete.

a) An attempt at an Eclipse application launch is unable to select the p2.manager application since it is not in the pull down.

b) Installing plugins and fragments with sources fails to match justj in the plugin filter.

c) Attempting to add justj.p2 as a MANIFEST.MF required bundle fails to find justj in the filter. Adding it manually gives a cannot be resolved error.

The configuration shows justj.p2 as Starting, and justj.tools as Resolved.

I could understand justj.tools being a bit invisible since it exports no packages, but the justj.p2 invisibility is wierd.

Workaround: checkout from GIT.

**Comment by ewillink** [comment]
After checking out there is some insight.

org.eclipse.justj.codegen has unsatisfied

```
Import-Package: org.apache.commons.compress.archivers.tar,
 org.apache.commons.compress.compressors.gzip
```

Neither an available bundle nor the associated JRE export package 'org.apache.commons.compress.archivers.tar'

But attempting to install from https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2024-03 shows no match to compress although https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2024-03/index.html suggests there should be. Checking the installed plugins the compress names are present as installed plugins, but the use of "tar" and "gzip" in the manifest suggests use of an inadequately supported reference.

**Comment by merks** [comment]
I tried that (installing into an Eclipse SDK installation) and it works for me and find it when creating a launcher:

![image](https://github.com/eclipse-justj/justj.tools/assets/208716/edd40d7b-ac0b-4657-aeda-6e85ab30d2bb)

When I launched it, and I've added all plugins to the workspace scope, I can even see the source clicking in the console on the stack trace:

![image](https://github.com/eclipse-justj/justj.tools/assets/208716/c26a4de5-cd55-48f2-9335-18b04c9f4deb)

Note PDE is looking at the target platform which might be defined as the running instance.  It's possible that this didn't update for you.  So you might try to Reload... it and you should look at the content to be sure the expected things are there:

![image](https://github.com/eclipse-justj/justj.tools/assets/208716/bcbd7d2f-e64c-4d4e-a5c2-1ca038414ade)

The bundle that provides the compress package is also present:

![image](https://github.com/eclipse-justj/justj.tools/assets/208716/3e8ab6b6-0909-4c5b-aa76-d95277dc72c3)

It (a bundle that satisfies the package requirements) must be present, otherwise p2 could not have installed.  So I see nothing wrong in/with JustJ that needs fixing.  Maybe a problem in PDE, but even for that, a problem I cannot reproduce.
